### PR TITLE
15 init the nodejs project

### PR DESCRIPTION
**Pull request by thanhduybui**
Duy add inti nodejs server code

### CODE REVIEW

**Comment by tuanhcmute** [comment]
@HongBeBong, Could you please give me some documentations to describe your code?

**Comment by thanhduybui** [comment]
> @HongBeBong, Could you please give me some documentations to describe your code?

[https://docs.google.com/document/d/17j7FJ6zLmdg8gcaOnU1vVzLwzFTRGnCceTrUVOSalBU/edit?hl=vi](url)

**Comment by tuanhcmute** [comment]
Hi @HongBeBong, Can you add some comments to run this service?

> > @HongBeBong, Could you please give me some documentations to describe your code?
> 
> [https://docs.google.com/document/d/17j7FJ6zLmdg8gcaOnU1vVzLwzFTRGnCceTrUVOSalBU/edit?hl=vi](url)

**Review by tuanhcmute — APPROVED** [review]
Done review

**Pull request merged**
